---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true
  tags: swarm

- name: Initialize Docker Swarm
  shell: >
        docker swarm init
        --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
  when: swarm_status.rc != 0
  run_once: true
  tags: swarm

- name: Get the Manager join-token
  shell: docker swarm join-token --quiet manager
  register: manager_token
  tags: swarm

- name: Get the worker join-token
  shell: docker swarm join-token --quiet worker
  register: worker_token
  tags: swarm

  ## TO ADD OTHERS MANAGERS IN THIS SWARM CLUSTER
  #- name: Add Managers to the Swarm
  #shell: "docker swarm join --token {{ hostvars[groups['weball'][0]]['manager_token']['stdout'] }} {{ hostvars[groups['weball'][0]]['ansible_default_ipv4']['address'] }}:2377"
  #when: swarm_status.rc != 0
